In [1]:
import numpy as np
import pandas as pd

import open_data

data = open_data.open()
df = data['df']

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV


In [3]:
regr = LogisticRegressionCV(scoring='neg_log_loss', penalty='elasticnet', cv=10, solver='saga', n_jobs=-1, Cs=np.power(10,np.linspace(-4,4,32)) , l1_ratios=np.power(10,np.linspace(-1,1,32))/(1 + np.power(10,np.linspace(-1,1,32))), max_iter=10000)
regr.fit(df.loc[:, df.columns != 'TARGET'].to_numpy(), df['TARGET'].to_numpy())

LogisticRegressionCV(Cs=array([1.00000000e-04, 1.81160919e-04, 3.28192787e-04, 5.94557071e-04,
       1.07710506e-03, 1.95129342e-03, 3.53498111e-03, 6.40400427e-03,
       1.16015530e-02, 2.10174801e-02, 3.80754602e-02, 6.89778538e-02,
       1.24960914e-01, 2.26380341e-01, 4.10112707e-01, 7.42963951e-01,
       1.34596032e+00, 2.43835410e+00, 4.41734470e+00, 8.00250228e+00,
       1.44974067e+01, 2.62...
       0.17367309, 0.19603511, 0.22050809, 0.24709725, 0.27575834,
       0.306391  , 0.33883449, 0.3728666 , 0.40820647, 0.44452166,
       0.4814393 , 0.5185607 , 0.55547834, 0.59179353, 0.6271334 ,
       0.66116551, 0.693609  , 0.72424166, 0.75290275, 0.77949191,
       0.80396489, 0.82632691, 0.84662469, 0.86493795, 0.88137097,
       0.89604488, 0.90909091]),
                     max_iter=10000, n_jobs=-1, penalty='elasticnet',
                     scoring='neg_log_loss', solver='saga')

In [4]:
regr.C_

array([0.22638034])

In [5]:
regr.l1_ratio_

array([0.306391])

In [6]:
regr.intercept_

array([-3.11215603])

In [7]:
regr.coef_

array([[-0.41844248, -0.17750631, -0.088934  , -0.07335309, -0.15937906,
        -0.09672799, -0.03659926,  0.01550435, -0.06330965, -0.06719953,
         0.        ,  0.        ,  0.01127787,  0.46882277,  0.27066779,
         0.01788762,  0.09949525,  0.20581858,  0.        ,  0.        ,
         0.        , -0.11365847,  0.48073138,  0.23283916, -0.23808144,
        -0.08144915, -0.11981365, -0.20108905]])

In [8]:
np.exp(regr.intercept_)/(1+np.exp(regr.intercept_))

array([0.04260861])